### ISSUE TITLE
output-file option is ignored

### ISSUE THREAD

**Issue by joshuacc** [sasstools/gulp-sass-lint#12]
I have the following (simplified) Gulp task:

``` js
gulp.task("scss", function () {
    return gulp.src(scssPath)
        .pipe(sassLint({
            options: {
                formatter: "junit",
                "output-file": "lint.xml"
            }
        }))
        .pipe(sassLint.format())
});
```

While the task does output the results with the `junit` formatter, it logs them to the console instead of writing them to a file as the [sass-lint documentation indicates](https://github.com/sasstools/sass-lint/blob/develop/docs/options/output-file.md).

**Comment by timschoch** [comment]
+1 
Have you already planned on fixing this any time soon?

**Comment by Snugug** [comment]
Once the next version of Sass Lint is released, I'll ensure everything is working for the gulp task and update accordingly
