### ISSUE TITLE
TypeError: Cannot read property 'line' of undefined

### ISSUE THREAD

**Issue by idflood** [sasstools/gulp-sass-lint#13]
When running gulp-sass-lint on my files I get the following error which seems to happen on the last rule. For exemple if I disable the `single-line-per-selector` rule the error happen on a different rule.

```
/project_dir/node_modules/sass-lint/lib/rules/single-line-per-selector.js:20
              'line': next.start.line,
                                ^
TypeError: Cannot read property 'line' of undefined
    at /project_dir/node_modules/sass-lint/lib/rules/single-line-per-selector.js:20:33
    at Node.forEach (/project_dir/node_modules/gonzales-pe/lib/node/basic-node.js:1:2053)
    at /project_dir/node_modules/sass-lint/lib/rules/single-line-per-selector.js:13:16
    at RootNode.traverseByType (/project_dir/node_modules/gonzales-pe/lib/node/root-node.js:1:1739)
    ...

# node --version
v0.12.5
```

**Comment by bgriffith** [comment]
Hey @idflood - As this appears to be an issue with sass-lint could you make an issue over there? https://github.com/sasstools/sass-lint . Also when you do, could you post your OS and if possible supply an example of the sass that's causing this error? Thanks.

**Comment by idflood** [comment]
Hi @bgriffith, 

Thanks I will post the issue on the sass-lint project in a few minutes with some more information. Here is the new issue: https://github.com/sasstools/sass-lint/issues/165
