### ISSUE TITLE
Didn't know how to use config file

### ISSUE THREAD

**Issue by edacchi-chonmage** [sasstools/gulp-sass-lint#14]
Hi, thank you for your great tools.
I feel good :)

But I have a little trouble, sorry.

I wanna use config file.
But I didn't know how to use it.

Like this.
https://github.com/sasstools/sass-lint/blob/master/lib/config/sass-lint.yml

If it's okay, will you write way to README ?

Thanks.

**Comment by samuelmartineau** [comment]
Hi,

Here is an example that works for me:

```
gulp.src(path.join(config.src, 'styles', '**' ,'*.s+(a|c)ss'))
    .pipe(sassLint({
        config: '.sass-lint.yml'
    }))
```

You just have to specify a path as config attribute.

**Comment by ewu02** [comment]
Didn't work for me with the latest sass-lint release. I've created a PR that should fix the issue.
https://github.com/sasstools/gulp-sass-lint/pull/15

**Comment by edacchi-chonmage** [comment]
Thanks a lot !
