### ISSUE TITLE
Linting Breaks on Syntax Error

### ISSUE THREAD

**Issue by popcorn245** [sasstools/gulp-sass-lint#2]
![image](https://cloud.githubusercontent.com/assets/4184680/9509475/90e20e30-4c25-11e5-9cc0-b48751a767bb.png)

When creating a syntactical error like the ones above.  The semi-colons are not caught at all by the linter, but doesn't break. However, when I "forget" a paren the linting breaks and gives the following error.

![image](https://cloud.githubusercontent.com/assets/4184680/9509757/f899180e-4c28-11e5-8c62-b1ce507aa84e.png)

**Comment by Snugug** [comment]
Gulp Sass Lint is a thin wrapper around [Sass Lint](https://github.com/sasstools/sass-lint/issues). Please re-file your issue there, and include the failing Sass.
