### ISSUE TITLE
Error thrown for property interpolation

### ISSUE THREAD

**Issue by SimonFinney** [sasstools/gulp-sass-lint#25]
An error is thrown when a variable is interpolated as a property:

``` scss
@mixin property-value($property, $value) {
  #{$property}: $value;
}

@include property-value('font-size', '1rem');
```

This outputs the following error:

```
events.js:141
  throw er; // Unhandled 'error' event
  ^
Error: Parsing error at scss/_mixins.scss: Please check validity of the block starting from line #
```

**Comment by DanPurdy** [comment]
This is an issue with `sass-lint` itself. There are a few issues open over there already but basically the AST we're using throws a parse error on interpolation at the moment

earliest issue is here
https://github.com/sasstools/sass-lint/issues/44

**Comment by SimonFinney** [comment]
:+1:
