### ISSUE TITLE
Change settings

### ISSUE THREAD

**Issue by dutchiexl** [sasstools/gulp-sass-lint#26]
I want to change the max nesting depth to 3, how would I be able to do that ?

**Comment by mjdurham** [comment]
sass-lint will read the rules from your .sass-lint.yml file.

If you want to change the the nesting-depth you can do so:

```
nesting-depth:
    - 2
    -
      max-depth: 3
```

You can read more about configuring sass-lint from the readme:
https://github.com/sasstools/sass-lint#rules
