### ISSUE TITLE
Install fails with unmet lodash dependency

### ISSUE THREAD

**Issue by quis** [sasstools/gulp-sass-lint#31]
Trying to install gulp-sass-lint fails because some of its dependencies are not met:

``` shell
> npm install gulp-sass-lint
npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "gulp-sass-lint"
npm ERR! node v5.7.0
npm ERR! npm  v3.7.5
npm ERR! No compatible version found: lodash.upperfirst@^3.0.0
npm ERR! Valid install targets:
npm ERR! 4.1.2, 4.1.1, 4.1.0, 4.0.2, 4.0.1, 4.0.0
npm ERR!
```

Any ideas why this is happening?

Travis output: https://travis-ci.org/alphagov/notifications-admin/builds/111962059

**Comment by kaigossel** [comment]
Same here. Seems to be related to https://github.com/lodash/lodash/issues/2059

**Comment by jvanaert** [comment]
looks like the sass-lint guys are hotfixing it right now
https://github.com/sasstools/sass-lint/pull/550

**Comment by jvanaert** [comment]
they fixed it. v1.5.1 is ok. just try to reinstall

**Comment by quis** [comment]
Works for me now (https://github.com/alphagov/notifications-admin/pull/205). Thanks all :+1:
