### ISSUE TITLE
Parsing error for interpolated variables

### ISSUE THREAD

**Issue by xiwcx** [sasstools/gulp-sass-lint#33]
``` scss
  @media #{ $width } {
```

results in the following error `Error: Parsing error at [filename].scss: Please check validity of the block starting from...`

Removing the spaces like so:

``` scss
  @media #{$width} {
```

Not huge, "spaces in interpolated variables" is probably an edge case, but figured it might be a small change to the parser.

**Comment by DanPurdy** [comment]
This is fixed since sass-lint 1.6
