### ISSUE TITLE
How to use a config file?

### ISSUE THREAD

**Issue by ghost** [sasstools/gulp-sass-lint#34]
The config options aren't explained in the Readme so i hoped the arguments will just be passed to sass-lint. But the following doesn't work:

`````` javascript
gulp.task('sass_lint', function() {
  return gulp.src('scss/**/*.s+(a|c)ss')
    .pipe(sassLint({
      'config-file': 'config/sass_lint.yml'
    }))
    .pipe(sassLint.format())
    .pipe(sassLint.failOnError())
});```
``````

**Comment by thestephenmarshall** [comment]
It won't load the file for you right now. You will have to get and parse the `.yml` config file yourself and pass the object into `sassLint`. 

``` javascript
var fs  = require('fs');
var path = require('path');
var yaml = require('js-yaml');

gulp.task('sass-lint', function () {
  var sassLintConfig = yaml.safeLoad(fs.readFileSync(path.join(__dirname, 'sass-lint.yml'), 'utf8'));
  return gulp.src('nope.sass')
    .pipe(sassLint(sassLintConfig))
    .pipe(sassLint.format())
    .pipe(sassLint.failOnError())
});
```

**Comment by vmasto** [comment]
I've found that it will, under a couple special circumstances:
- The file needs to be named exactly `.sass-lint.yml` (it must be a dotfile with that name)
- The file needs to be on the same directory as your gulpfile

Then you can do:

``` js
gulp.task('sass-lint', function () {
  return gulp.src('nope.scss')
    .pipe(sassLint({
       configFile: '.sass-lint.yml'
     }))
    .pipe(sassLint.format())
    .pipe(sassLint.failOnError())
});
```

This way you don't have to load `js-yaml` in your pipeline.
**EDIT**: Actually, the `{configFile: '.sass-lint.yml'}` is not needed in the above code, the linter picks the file up automatically if you do it this way.

**Comment by BrendanBerkley** [comment]
After playing around with the solutions above, I learned that @vmasto's comment is correct. It wasn't working for me, though, and what I found is that if my `.sass-lint.yml` file was bad, it would fail silently and revert to the default rules. In my case I had YAML that didn't follow the rules. Once I had a properly-formed config file, it started to work.

**Comment by ghost** [comment]
The solution is still not acceptable for me. I have various other config files and i want then all in a separate folder. It's quite common gulp plugins just pass the config object to the pure node module implementation, so it will support exactly the same options.

**Comment by aseem2625** [comment]
My gulp is:

```
var gulp = require('gulp');
var sassLint = require('gulp-sass-lint');
//var yaml = require('js-yaml'); //I checked the earlier posts but I am not using this.


gulp.task('sasslint', function () {
    gulp.src(['src/scss/**/*.s+(a|c)ss', '!src/scss/vendor/**/*.s+(a|c)ss'])
        .pipe(sassLint({'config': '.sass-lint.yml'}))
        .pipe(sassLint.format())
        .pipe(sassLint.failOnError())
});
```

**And my ".sass-lint.yml" is in same hierarchy as "gulpfile.js."**
If you want to put "sass-lint.yml" is config folder where config folder is in same hierarchy with "gulpfile.js"
Then make it as:

```
.pipe(sassLint({'config': 'config/sass-lint.yml'})) //This too works for me
```

Only thing that doesn't work for me in yml is

```
files:
  include: './src/scss/**/*.scss'
  ignore:
      - './src/scss/vendor/**/*.s+(a|c)ss' 
```

Check this out. I've not added anything separately for Make sure your paths and file names are correct.

**Also, someone please tell me that how to ignore files through yml. Currently I am doing like:**

```
    gulp.src(['src/scss/**/*.s+(a|c)ss', '!src/scss/vendor/**/*.s+(a|c)ss'])
```

**Comment by michaelBenin** [comment]
This is what a valid config looks like:

`{
      options: {
        'config-file': './gulpfile.babel.js/configs/sass-lint.yaml'
      }
    }`

Where options are the configs allowed from this library:

https://github.com/sasstools/sass-lint#options

Can someone update the readme to show all allowed config options?

**Comment by michaelBenin** [comment]
Almost forgot this is how it's used:

```
import gulp from 'gulp';
import config from '../configs/config';
const sassLint = require('gulp-sass-lint');

gulp.task('sass-lint', function lintSass() {
  gulp.src(['./src/**/*.scss'])
    .pipe(sassLint({ options: { 'config-file': './gulpfile.babel.js/configs/sass-lint.yaml' } })
    .pipe(sassLint.format())
    .pipe(sassLint.failOnError());
});
```

**Comment by michaelBenin** [comment]
I figured this out by digging through the source of sass-lint.

**Comment by DanPurdy** [comment]
I've just submitted a PR that should fix / clarify this for good. I've also put a new method into sass-lint to handle this specifically so once sass-lint 1.8 is out then this will be good to go see [here](https://github.com/sasstools/sass-lint/pull/711). 

For now the way @michaelBenin is doing this is perfectly valid though he's missing a closing parenthesis it should be 
`.pipe(sassLint({ options: { 'config-file': './gulpfile.babel.js/configs/sass-lint.yaml' } }))` 👍

**Comment by DanPurdy** [comment]
We'll be releasing the updates here once sass lint 1.8 is in the wild
