### ISSUE TITLE
Can I disable the linter via source?

### ISSUE THREAD

**Issue by AmmarCodes** [sasstools/gulp-sass-lint#36]
Hey, 

I want to ask you please about disabling the linting on specific lines/blocks, scss-lint already have this implemented [here](https://github.com/brigade/scss-lint/#disabling-linters-via-source).

Tried the same method but didn't work, the rules are not ignored.

Anything to solve this?

**Comment by Snugug** [comment]
https://github.com/sasstools/sass-lint/issues/70

Please follow this issue in the Sass Lint issue queue
