### ISSUE TITLE
Does not parse manifest file

### ISSUE THREAD

**Issue by zslabs** [sasstools/gulp-sass-lint#40]
Hi all,
I noticed something that's a bit unexpected compared to other packages.

I have a `app.scss` manifest file that simply `@imports` all of my other Sass components. If I pass this linter into my normal styles build task, it doesn't read any of the sub-files. I would expect this to be able to parse all of these files for me. Do I need to write a separate task for just the linting?

**Comment by DanPurdy** [comment]
We don't actually read the Sass and act on it we just generate a tree of tokens and act upon them. A linter shouldn't compile/transpile code first as we don't care about the outcome of what has been written only the initial context.

You'll need to specify all of the files in your manifest file as targets for `sass-lint` which you must be doing as part of your build task anyway in order for Sass/libsass to understand what to import?

In the case of `gulp-sass-lint` it just lints the contents of every file passed to it, so if you only send your manifest file to it that is the only file it will read.

Hopefully that's what you meant?

**Comment by zslabs** [comment]
Yep, makes perfect sense. I was thinking of this in the wrong way, thanks for clarifying!
