### ISSUE TITLE
Result shows the wrong line numbers

### ISSUE THREAD

**Issue by kimblim** [sasstools/gulp-sass-lint#41]
Here's an example of a file:

```
/* Utilities */
@import '../Global/animate';
@import '../Global/grid';
@import '../Global/utils';

/* Helpers */
@import 'helpers/colors';
@import 'helpers/helper-classes';
@import 'helpers/z-index';

/* Iconfont*/
@import 'generated/iconfont';

/* Base */
@import 'base/animation';
@import 'base/default';
@import 'base/typography';
@import 'base/utils';
@import 'base/rich-text';

/* Settings */
@import 'base/settings';
```

Which outputs  the following errors:

> 1:1  warning  Multiline style comments should not be used  no-css-comments
> 11:1  warning  Multiline style comments should not be used  no-css-comments
> 21:1  warning  Multiline style comments should not be used  no-css-comments
> 27:1  warning  Multiline style comments should not be used  no-css-comments
> 41:1  warning  Multiline style comments should not be used  no-css-comments

Expected output should be:

> 1:1  warning  Multiline style comments should not be used  no-css-comments
> 6:1  warning  Multiline style comments should not be used  no-css-comments
> 11:1  warning  Multiline style comments should not be used  no-css-comments
> 14:1  warning  Multiline style comments should not be used  no-css-comments
> 21:1  warning  Multiline style comments should not be used  no-css-comments

Has anyone else experienced this issue and does anyone have a fix for it?

**Comment by DanPurdy** [comment]
Hi @kimblim Are you on windows? Using CRLF line endings?

If so you need to make sure you're using sass-lint 1.6.0 and up so reinstall your node modules is the easiest solution. We fixed an issue with CRLF line endings in the AST we're using from 1.6.0 and up.

**Comment by kimblim** [comment]
That was exactly the problem (not that I'm on Windows, but some team-members are).

Thanx!

**Comment by DanPurdy** [comment]
Awesome, 1.6 has a much much more stable platform and a lot of work is going into making future versions even better now so I'm glad this solved your problem! :+1:
