### ISSUE TITLE
Error when using attribute-selector in combination with @At-root directive

### ISSUE THREAD

**Issue by siiron** [sasstools/gulp-sass-lint#50]
It seems that gulp-sass-lint reports a problem when using an attribute selector in combination with the @at-root directive.

Using just a tag without attribute-selector seems to work fine.
[Here is a gist](http://www.sassmeister.com/gist/31fff192b3131bc63737323ccfa4a438)

**Comment by DanPurdy** [comment]
Can you please report this at the sass-lint repo instead. gulp-sass-lint only consumes sass-lint https://github.com/sasstools/sass-lint
