### ISSUE TITLE
Ignores sassLint(options)

### ISSUE THREAD

**Issue by sergey-shpak** [sasstools/gulp-sass-lint#55]
Hey!

``` javascript
.pipe(sassLint({
    options: {
        formatter: 'visualstudio',
        'merge-default-rules': false
    }
}))
```

Gets 'stylish' output, looks like user options are ignored

**Comment by mattbrooks2010** [comment]
@DanPurdy [this change](https://github.com/sasstools/gulp-sass-lint/commit/aed26ed7f8630cff684e63042cd0a08fedb4274c#diff-168726dbe96b3ce427e7fedce31bb0bcL36) is what broke this. It is [passing undefined as the second parameter](https://github.com/sasstools/gulp-sass-lint/blob/master/index.js#L73) to `sassLint.outputResults`.
