### ISSUE TITLE
Remove deprecated module gulp-util

### ISSUE THREAD

**Issue by Frank3K** [sasstools/gulp-sass-lint#83]
Replace deprecated dependency gulp-util

[`gulp-util`](https://www.npmjs.com/package/gulp-util) has been recently deprecated. Continuing to use this dependency may prevent the use of your library with the latest release of Gulp 4 so **it is important to replace `gulp-util`**.

The [README.md](https://github.com/gulpjs/gulp-util) lists alternatives for all the components so a simple replacement should be enough.

Your package is one of the most popular packages still relying on `gulp-util`, it would be good to publish a fixed version to npm as soon as possible.

See:
- https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
- https://github.com/gulpjs/gulp-util/issues/143

**Comment by theenoahmason** [comment]
> Your package is one of the most popular packages still relying on gulp-util, it would be good to publish a fixed version to npm as soon as possible.

And we love you for it! Please make this fix as soon as possible. 🙏

**Comment by jameelmoses** [comment]
Any update here?

**Comment by laurence702** [comment]
Is there a quick fix i can use to solve this issue :
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
Ive read the Blog on Medium but wasnt too help. are there alternatives?

**Comment by jameelmoses** [comment]
@laurence702 it's already been fixed. you need to upgrade the package locally in your project.
