### ISSUE TITLE
minimist package vulnerability

### ISSUE THREAD

**Issue by IdanAdar** [sasstools/gulp-sass-lint#92]
```
Low           │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ minimist                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=0.2.1 <1.0.0 || >=1.2.3                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ gulp-sass-lint [dev]                                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ gulp-sass-lint > sass-lint > gonzales-pe-sl > minimist       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/1179                  
```

@xzyfer

**Comment by IdanAdar** [comment]
Thanks @xzyfer - it looks like there are issues with generating a new npm release?

**Comment by IdanAdar** [comment]
Thanks @xzyfer - it looks like there are issues with generating a new npm release?

**Comment by IdanAdar** [comment]
@xzyfer Can you please open this ticket until you'll actually release a fixed version?
I remind you this package is used in the wild and is vulnerable... I would really appreciate it if you could resolve the build issue...

**Comment by dippas** [comment]
Starting today I'm having this issue also. And I always keep my dependencies up to date

**Comment by IdanAdar** [comment]
Unfortunately security is not a top priority, it seems.

**Comment by dippas** [comment]
This has been fixed late March but so far no update in npm package.  @xzyfer  this is my only vulnerability.

**Comment by dippas** [comment]
@xzyfer  any news on this please?

**Comment by dippas** [comment]
@Snugug   can you take a look at this?

**Comment by dippas** [comment]
Almost a year after this issue was open and even being fixed It was **NOT UPDATED** in npm package. @xzyfer  @Snugug  can you please update the npm package
